from userbot import bot as MUNNAgalaxy
from userbot.utils import admin_cmd as choot

x = True
@MUNNAgalaxy.on(choot(pattern="bsdk"))
async def yashraid(event):
    while x != False:
       
        await event.delete()
        kek = event.chat_id
        await MUNNAgalaxy.send_message(kek, "TERI MA KI CHOOXT MAARUU BSDKEE")
        await MUNNAgalaxy.send_message(kek, "TERE AMMA KA MADARBHOSDA")
        await MUNNAgalaxy.send_message(kek, "HATT JHAATTUUU")
        await MUNNAgalaxy.send_message(kek, "TERIII MAA KI CHUTTT")
        await MUNNAgalaxy.send_message(kek, "CHINNNNALLL KEE SADE HUE LODDEE")
        await MUNNAgalaxy.send_message(kek, "GAANNNDDD MEEE DANNDDAAA DAAL LEEE MADARCHOOODDD")
        await MUNNAgalaxy.send_message(kek, "DALLOOOO HOOO TUMMM VHSSDKDKKK")
        await MUNNAgalaxy.send_message(kek, "JHHAATTT UGIII NHII H")
        await MUNNAgalaxy.send_message(kek, "ORRR BAAAPPP SE BAKCHODIIII KRR RHE HO")
        await MUNNAgalaxy.send_message(kek, "ABEEE GAANNNDDDD KEEE BAAL")
        await MUNNAgalaxy.send_message(kek, "ABEE GANNDUUU")
        await MUNNAgalaxy.send_message(kek, "TERRIII MAA BHOOSSDDDAA CHHODUUU")
        await MUNNAgalaxy.send_message(kek, "RANDDIIIII KEEE PILLEEE")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "MERREE KATEE HUE JHAAT KE BAAL")
        await MUNNAgalaxy.send_message(kek, "TERRIII MAA CHUTTT KE BAALL")
        await MUNNAgalaxy.send_message(kek, "TERRRIII MAA")
        await MUNNAgalaxy.send_message(kek, "KOOO PELUUU")
        await MUNNAgalaxy.send_message(kek, "BINNAAA CONDUUMMM")
        await MUNNAgalaxy.send_message(kek, "KEE BSDIWALEEEE")
        await MUNNAgalaxy.send_message(kek, "TERRIII BHNNN KO SUARRR CHODDEEE")
        await MUNNAgalaxy.send_message(kek, "CHHIINAARRR LODEEEE")
        await MUNNAgalaxy.send_message(kek, "TERRIII MAAAA")
        await MUNNAgalaxy.send_message(kek, "SE NAGGAAA NAACH")
        await MUNNAgalaxy.send_message(kek, "KRWAAOUNGA MADARCHODDD")
        await MUNNAgalaxy.send_message(kek, "TERRIII MAA KI")
        await MUNNAgalaxy.send_message(kek, "CHUTT PRRRRRRR")
        await MUNNAgalaxy.send_message(kek, "CHHAAAPPPAAA MARUUU LODEEE")
        await MUNNAgalaxy.send_message(kek, "TERRIII MAA KOO")
        await MUNNAgalaxy.send_message(kek, "LUNDDD PRRR UCHHAALUUU")
        await MUNNAgalaxy.send_message(kek, "TERRRIII MAAA")
        await MUNNAgalaxy.send_message(kek, "KIII CHUCHIII KAAA")
        await MUNNAgalaxy.send_message(kek, "KAAAA SARA DDDUDDD PIII JAAOUNGA")
        await MUNNAgalaxy.send_message(kek, "MADRRRCHHHOODDD")
        await MUNNAgalaxy.send_message(kek, "JHHAATUUU")
        await MUNNAgalaxy.send_message(kek, "BHOSSDIIIIKEEE DALLEE")
        await MUNNAgalaxy.send_message(kek, "RANDWEEE")
        await MUNNAgalaxy.send_message(kek, "CHAKKE")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "DOOGGLEEE")
        await MUNNAgalaxy.send_message(kek, "BHOOSSDDDKKKKK")
        await MUNNAgalaxy.send_message(kek, "TEERRRIIII MMMAA")
        await MUNNAgalaxy.send_message(kek, "KOO CHOOODDUUUU")
        await MUNNAgalaxy.send_message(kek, "CHINARRRRR")
        await MUNNAgalaxy.send_message(kek, "GANDDMAREE")
        await MUNNAgalaxy.send_message(kek, "5 RS ME")
        await MUNNAgalaxy.send_message(kek, "GAANNNDDD DENNEEE")
        await MUNNAgalaxy.send_message(kek, "WALEEEE GAAANDUUU")
        await MUNNAgalaxy.send_message(kek, "TERRRIII")
        await MUNNAgalaxy.send_message(kek, "GAAANDDDD")
        await MUNNAgalaxy.send_message(kek, "FADDDNEEEE")
        await MUNNAgalaxy.send_message(kek, "WWAAALEEEE")
        await MUNNAgalaxy.send_message(kek, "TEEREEE BAAAPP")
        await MUNNAgalaxy.send_message(kek, "HHH HUMMMMM")
        await MUNNAgalaxy.send_message(kek, "MAADDRRRCCCHHOODDD")
        await MUNNAgalaxy.send_message(kek, "BHOSSDDDIKKEEEEE")
        await MUNNAgalaxy.send_message(kek, "MUNNA OP")
        await MUNNAgalaxy.send_message(kek, "SEEE HHHH HUUMM")
        await MUNNAgalaxy.send_message(kek, "ACCCHHEEEE ACCCHOO")
        await MUNNAgalaxy.send_message(kek, "KIIII MAAAA CCCHOOODDD")
        await MUNNAgalaxy.send_message(kek, "DDETTEEEE HH  DALLEEE")
        await MUNNAgalaxy.send_message(kek, "TUUU TUUU KON SAAA")
        await MUNNAgalaxy.send_message(kek, "KHEETTT KII RADISH")
        await MUNNAgalaxy.send_message(kek, "HHHH")
        await MUNNAgalaxy.send_message(kek, "LOODDUUUUUU")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "MUNNA KE")
        await MUNNAgalaxy.send_message(kek, "NAAAMMM SEEEEE")
        await MUNNAgalaxy.send_message(kek, "ACCGEEEE AACHEEEE")
        await MUNNAgalaxy.send_message(kek, "DARTEEE H")
        await MUNNAgalaxy.send_message(kek, "PAANTT MEEEE")
        await MUNNAgalaxy.send_message(kek, "MUUTTT DETE H")
        await MUNNAgalaxy.send_message(kek, "MAADRRRCHODDD")
        await MUNNAgalaxy.send_message(kek, "YEEEE AAYNGEE")
        await MUNNAgalaxy.send_message(kek, "BAAAP SE")
        await MUNNAgalaxy.send_message(kek, "LADNEEEE BHNCHOODDDDDD")
        await MUNNAgalaxy.send_message(kek, "MADDRRRCHODDDDD")
        await MUNNAgalaxy.send_message(kek, "TERRIII AUKKAAT")
        await MUNNAgalaxy.send_message(kek, "CHULLUUU BHARR")
        await MUNNAgalaxy.send_message(kek, "MUUTTTTT KIIII")
        await MUNNAgalaxy.send_message(kek, "HHHHH BETICHODDDD")
        await MUNNAgalaxy.send_message(kek, "USI MEEEEE JAAAA KEEEE DDDUUBBBB MARRRRR")
        await MUNNAgalaxy.send_message(kek, "BHNNNN KEEEE LODDEEEEE")
        await MUNNAgalaxy.send_message(kek, "CHIPAAKIII")
        await MUNNAgalaxy.send_message(kek, "KIII BHEEEGGIIII")
        await MUNNAgalaxy.send_message(kek, "CHHUTTTTT SIII")
        await MUNNAgalaxy.send_message(kek, "SHAKALLLL KEE")
        await MUNNAgalaxy.send_message(kek, "GHOODEEE")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "KIII GAAAANDDDD")
        await MUNNAgalaxy.send_message(kek, "TERRR BAPPPP")
        await MUNNAgalaxy.send_message(kek, "HHHHH MUNNA")
        await MUNNAgalaxy.send_message(kek, "INSEEE NAAAAA KRNA")
        await MUNNAgalaxy.send_message(kek, "PANGGGAAAA")
        await MUNNAgalaxy.send_message(kek, "VARNAAAAAAAA")
        await MUNNAgalaxy.send_message(kek, "KARRR DEGAAAAA")
        await MUNNAgalaxy.send_message(kek, "NANGAAAAA")
        await MUNNAgalaxy.send_message(kek, "JEESSEEEE")
        await MUNNAgalaxy.send_message(kek, "TERRRIIII MAAAAA")
        await MUNNAgalaxy.send_message(kek, "TERREEE KARMOOO")
        await MUNNAgalaxy.send_message(kek, "KEEE FALLL MUJHSEEEE")
        await MUNNAgalaxy.send_message(kek, "CHUDDDD KRRR BHOOOGG")
        await MUNNAgalaxy.send_message(kek, "RHIIII HHH GAAANDUUU")
        await MUNNAgalaxy.send_message(kek, "ISSLSIYYEEEE KHTTEE")
        await MUNNAgalaxy.send_message(kek, "HHHH BAAAPP")
        await MUNNAgalaxy.send_message(kek, "SEE NOO")
        await MUNNAgalaxy.send_message(kek, "PANGAAAAA")
        await MUNNAgalaxy.send_message(kek, "KRRRRR DIYAAAAA")
        await MUNNAgalaxy.send_message(kek, "JATAAA HHHH")
        await MUNNAgalaxy.send_message(kek, "NANGAAAAAA")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "ORRRR BETEEE")
        await MUNNAgalaxy.send_message(kek, "KAHA KAHA ")
        await MUNNAgalaxy.send_message(kek, "SE GAAANDDDD")
        await MUNNAgalaxy.send_message(kek, "DE KRRR AAAAA")
        await MUNNAgalaxy.send_message(kek, "RHEEE HOOO BHNKEEE")
        await MUNNAgalaxy.send_message(kek, "LAWDEEEEE")
        await MUNNAgalaxy.send_message(kek, "BHANNNNN KEEEE TAKKERE")
        await MUNNAgalaxy.send_message(kek, "BHAAIIIII KIII")
        await MUNNAgalaxy.send_message(kek, "AAULAAADDD")
        await MUNNAgalaxy.send_message(kek, "BINAAA JHATTT KEEE BAAAL")
        await MUNNAgalaxy.send_message(kek, "BHOOOSRIII WALA")
        await MUNNAgalaxy.send_message(kek, "BURRR CHODII")
        await MUNNAgalaxy.send_message(kek, "TOOHRRR MAIII")
        await MUNNAgalaxy.send_message(kek, "KOOO CHODUU")
        await MUNNAgalaxy.send_message(kek, "BHNCHODDD")
        await MUNNAgalaxy.send_message(kek, "TOHRRRR BURIYAAAA")
        await MUNNAgalaxy.send_message(kek, "FHAADDD DAIBBB")
        await MUNNAgalaxy.send_message(kek, "CHALLL TUU")
        await MUNNAgalaxy.send_message(kek, "HIII BTA")
        await MUNNAgalaxy.send_message(kek, "GANDDUUUU")
        await MUNNAgalaxy.send_message(kek, "TERRIIII GANDD")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "KESE MARRUUU")
        await MUNNAgalaxy.send_message(kek, "BTAOOO GANDWEE")
        await MUNNAgalaxy.send_message(kek, "LUNDDDD CHUSSSSS")
        await MUNNAgalaxy.send_message(kek, "LEEEEEE MERAAAAA")
        await MUNNAgalaxy.send_message(kek, "TERRIIII MAAAAA")
        await MUNNAgalaxy.send_message(kek, "KEE NAKHREEEEE BHUT HHHHH")
        await MUNNAgalaxy.send_message(kek, "TERIIII MAAA")
        await MUNNAgalaxy.send_message(kek, "KEEE BHOSDEEE")
        await MUNNAgalaxy.send_message(kek, "SEEEE BHIII")
        await MUNNAgalaxy.send_message(kek, "KHUNNNNN NIKALLL")
        await MUNNAgalaxy.send_message(kek, "DIYAAAA MADRCHODDDDD")
        await MUNNAgalaxy.send_message(kek, "DEKHHH LEEE APNEE")
        await MUNNAgalaxy.send_message(kek, "BAAPP KAA DUMM")
        await MUNNAgalaxy.send_message(kek, "FHATEEEE ")
        await MUNNAgalaxy.send_message(kek, "CONDOM KEE")
        await MUNNAgalaxy.send_message(kek, "NATIJEEEE")
        await MUNNAgalaxy.send_message(kek, "MACHARRR KEEEE GANDDD")
        await MUNNAgalaxy.send_message(kek, "KOTHEYYY MEEE")
        await MUNNAgalaxy.send_message(kek, "NACHNEEE WALEEE")
        await MUNNAgalaxy.send_message(kek, "LODUUUUU")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "KOTHEYYYY MEEE")
        await MUNNAgalaxy.send_message(kek, "MAAAA NACHWANEEE")
        await MUNNAgalaxy.send_message(kek, "WALEEEEEE")
        await MUNNAgalaxy.send_message(kek, "KOTHEYYYY KIII FAMOUSSS")
        await MUNNAgalaxy.send_message(kek, "RANDDIIIII")
        await MUNNAgalaxy.send_message(kek, "HHHH TERIIIII")
        await MUNNAgalaxy.send_message(kek, "MAAAAAA KIII CHUTTT")
        await MUNNAgalaxy.send_message(kek, "BDIII MJBUTTTTTT")
        await MUNNAgalaxy.send_message(kek, "APNIIIII MAAAA")
        await MUNNAgalaxy.send_message(kek, "KAAA RATEEE")
        await MUNNAgalaxy.send_message(kek, "SUNNNN BETICHODDDD")
        await MUNNAgalaxy.send_message(kek, "10 KA DHAKKAA")
        await MUNNAgalaxy.send_message(kek, "20 KII CHOOT")
        await MUNNAgalaxy.send_message(kek, "KHUNNNNN NIKLAAA")
        await MUNNAgalaxy.send_message(kek, "TOOOOOO")
        await MUNNAgalaxy.send_message(kek, "100 KAAA NOTEEEE")
        await MUNNAgalaxy.send_message(kek, "YE H TERI")
        await MUNNAgalaxy.send_message(kek, "MAAAA KAAA")
        await MUNNAgalaxy.send_message(kek, "GLOBALLLL")
        await MUNNAgalaxy.send_message(kek, "RATEEEEE")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "ORRR BHOSDDIIIKEEEE")
        await MUNNAgalaxy.send_message(kek, "TERIII MAAA")
        await MUNNAgalaxy.send_message(kek, "SASTIII RANDIII")
        await MUNNAgalaxy.send_message(kek, "HHHH MADRCHODDDD")
        await MUNNAgalaxy.send_message(kek, "FHATEEE CONDOM KE SAUDAGAR")
        await MUNNAgalaxy.send_message(kek, "FHATEEE CONDOM KI AULAAAD")
        await MUNNAgalaxy.send_message(kek, "KUTTTEEEE")
        await MUNNAgalaxy.send_message(kek, "KOOOO GANNDDD")
        await MUNNAgalaxy.send_message(kek, "DENEEE WALEEEE")
        await MUNNAgalaxy.send_message(kek, "CHAKKEEEEE")
        await MUNNAgalaxy.send_message(kek, "YEEEE LADENGEEE")
        await MUNNAgalaxy.send_message(kek, "BAAPPP SEEE")
        await MUNNAgalaxy.send_message(kek, "JINKIIII KHUDDDD KI")
        await MUNNAgalaxy.send_message(kek, "AUKAATTTTT")
        await MUNNAgalaxy.send_message(kek, "MUTTT JITNIII")
        await MUNNAgalaxy.send_message(kek, "BHIII NHIIII HHHH")
        await MUNNAgalaxy.send_message(kek, "INHEEE UDNAAA H")
        await MUNNAgalaxy.send_message(kek, "JINKEEE DHNGGGG")
        await MUNNAgalaxy.send_message(kek, "SEEE BAAAL")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "NHIII UGEEEE")
        await MUNNAgalaxy.send_message(kek, "ORRR BATEEE")
        await MUNNAgalaxy.send_message(kek, "DEKHOOO ZRAAAA")
        await MUNNAgalaxy.send_message(kek, "INNNN GANDWOOO KII")
        await MUNNAgalaxy.send_message(kek, "TERI BHN KA BHOSXDA FAAD DIA MADARCHOD")
        await MUNNAgalaxy.send_message(kek, "TERI BHN KI GANXD ME DYNAMTE LAGA KE UDA DIA")
        await MUNNAgalaxy.send_message(kek, "MUNNA OP HAI HM BAAP BOLTE HMKO")
        await MUNNAgalaxy.send_message(kek, "TERI MAA KO CHOODUU")
        await MUNNAgalaxy.send_message(kek, "MAADARCHODD")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "ROJJ MERE")
        await MUNNAgalaxy.send_message(kek, "LODEE PE")
        await MUNNAgalaxy.send_message(kek, "AAKEE UCHALTII")
        await MUNNAgalaxy.send_message(kek, "HAII")
        await MUNNAgalaxy.send_message(kek, "TERI GANND TOD DI JAYEGI MADDRCHOOD")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "TERI MAA KA BHOOSSDA FAADU DOGLE MADRCHODD")
        await MUNNAgalaxy.send_message(kek, "BEHEN")
        await MUNNAgalaxy.send_message(kek, "KII CHUTTT")
        await MUNNAgalaxy.send_message(kek, "AUR GANND")
        await MUNNAgalaxy.send_message(kek, "MAR MARKE")
        await MUNNAgalaxy.send_message(kek, "EK KAR DIYAA")
        await MUNNAgalaxy.send_message(kek, "MUNNA MEMBER IS ALWAYS ON FIRE")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "MADERRRRCHODDO")
        await MUNNAgalaxy.send_message(kek, "TUM SABB KAA")
        await MUNNAgalaxy.send_message(kek, " BAAAP HAII")
        await MUNNAgalaxy.send_message(kek, "MUNNA HAI HM HMKO KAHTE H OP AUR BETE TUM MUNNA KE LAND KI TOPI")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "TERI GAMD TOD DI JAYEGI MADDRCHOD")
        await MUNNAgalaxy.send_message(kek, "KII MAA")
        await MUNNAgalaxy.send_message(kek, "KAA RAPEE")
        await MUNNAgalaxy.send_message(kek, "KR DIYAA")
        await MUNNAgalaxy.send_message(kek, "EKDUM GHODII")
        await MUNNAgalaxy.send_message(kek, "BANAKEE")
        await MUNNAgalaxy.send_message(kek, " CHODAA")
        await MUNNAgalaxy.send_message(kek, "MUNNA NE CHOD DIA TUJE")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "TUMHARII MAA KO")
        await MUNNAgalaxy.send_message(kek, "AISAA")
        await MUNNAgalaxy.send_message(kek, "CHODAA GHARR")
        await MUNNAgalaxy.send_message(kek, "TAKK")
        await MUNNAgalaxy.send_message(kek, "APNII CHUTT")
        await MUNNAgalaxy.send_message(kek, "PAKADD")
        await MUNNAgalaxy.send_message(kek, "KEE")
        await MUNNAgalaxy.send_message(kek, "ROTII")
        await MUNNAgalaxy.send_message(kek, "GAEE HAII")
        await MUNNAgalaxy.send_message(kek, "AB BHII")
        await MUNNAgalaxy.send_message(kek, "TIME HAI")
        await MUNNAgalaxy.send_message(kek, "HUME BAAP")
        await MUNNAgalaxy.send_message(kek, "BOLDOO")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "AISE BHII")
        await MUNNAgalaxy.send_message(kek, "TUMHARII MAA")
        await MUNNAgalaxy.send_message(kek, "TO ROZZ HUMSEE")
        await MUNNAgalaxy.send_message(kek, "CHUDTI HI HAII")
        await MUNNAgalaxy.send_message(kek, "ROZZ KALAPTI HAII")
        await MUNNAgalaxy.send_message(kek, "WO DEKHO")
        await MUNNAgalaxy.send_message(kek, "TERA BAAP")
        await MUNNAgalaxy.send_message(kek, "BETHA HAI")
        await MUNNAgalaxy.send_message(kek, "GHODEE PEE")
        await MUNNAgalaxy.send_message(kek, "TERI GANND TOD DI JAYEGI MADDRCHOD TUMHARA BAAP HU ME MUNNA WALE GANND FAAD KE RAKH DENGE TERI MADARCHOOD")
        await MUNNAgalaxy.send_message(kek, "TUMHARII")
        await MUNNAgalaxy.send_message(kek, "MAA")
        await MUNNAgalaxy.send_message(kek, "MEREEE")
        await MUNNAgalaxy.send_message(kek, "LODEEE")
        await MUNNAgalaxy.send_message(kek, "OHH YEAHHH")
        await MUNNAgalaxy.send_message(kek, "KYAA MASTT")
        await MUNNAgalaxy.send_message(kek, "MAZAA DETI")
        await MUNNAgalaxy.send_message(kek, "HAII")
        await MUNNAgalaxy.send_message(kek, "TUMHARII MAA")
        await MUNNAgalaxy.send_message(kek, "MUNNA NE TUMHARI BHN KO PURII RAT CHOXDAAA ")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "TERI MAKI CHOOT 3 BAAR")
        await MUNNAgalaxy.send_message(kek, "BAAP HAII H HUM")
        await MUNNAgalaxy.send_message(kek, "TERII MAA")
        await MUNNAgalaxy.send_message(kek, "KOO")
        await MUNNAgalaxy.send_message(kek, "BHUTT GANDAA CHODAA")
        await MUNNAgalaxy.send_message(kek, "BHOXDIKE AUKAAT BNA FRR MUNNA SE PANGE LENA")
        await MUNNAgalaxy.send_message(kek, "GANDUUU")
        await MUNNAgalaxy.send_message(kek, "KIII MAAA")
        await MUNNAgalaxy.send_message(kek, "KIII CHUTTT")
        await MUNNAgalaxy.send_message(kek, "LETE SAMAY")
        await MUNNAgalaxy.send_message(kek, "USKII")
        await MUNNAgalaxy.send_message(kek, "CHUTTT")
        await MUNNAgalaxy.send_message(kek, "MEEE MAINEE")
        await MUNNAgalaxy.send_message(kek, "GARAM LOHEE")
        await MUNNAgalaxy.send_message(kek, "KAA SARIYAA")
        await MUNNAgalaxy.send_message(kek, "DAAL DIYAA")
        await MUNNAgalaxy.send_message(kek, "KALAP GYII")
        await MUNNAgalaxy.send_message(kek, "TERI BHN KE GORE BOOBS AAHAAH AAH AAHA AAAHA AAHA AAAHH")
        await MUNNAgalaxy.send_message(kek, "TERI MA KI CHOOXT FAD DI MENE BHOOSSDIKE ")
        await MUNNAgalaxy.send_message(kek, "TERE BAAP")
        await MUNNAgalaxy.send_message(kek, "RHEGE HUM")
        await MUNNAgalaxy.send_message(kek, "HUMESAA")
        await MUNNAgalaxy.send_message(kek, "ROZZ TMHARIII")
        await MUNNAgalaxy.send_message(kek, "MAA KOO")
        await MUNNAgalaxy.send_message(kek, "GHODII BANAKEE")
        await MUNNAgalaxy.send_message(kek, "CHODEEEGEE")
        await MUNNAgalaxy.send_message(kek, "TERI GAMD TOD DI JAYEGI MADDRCHOD KIII")
        await MUNNAgalaxy.send_message(kek, "MAAAA")
        await MUNNAgalaxy.send_message(kek, "CHUDD GYIII")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "TERA ASLIII")
        await MUNNAgalaxy.send_message(kek, "BAAAP")
        await MUNNAgalaxy.send_message(kek, "MAIN HI HUINN MUNNA SE")
        await MUNNAgalaxy.send_message(kek, "MERAA NAJAYAZ🤣")
        await MUNNAgalaxy.send_message(kek, "BETA HAI TUU")
        await MUNNAgalaxy.send_message(kek, "TERI MAA KI CHUUTTT AHHHH GZB BHSODDA BNA DIYAA")
        await MUNNAgalaxy.send_message(kek, "HUMSE BAKCHODI NA KRRR TELE PR RHNE LAYAK NHI BACHEGA")
        await MUNNAgalaxy.send_message(kek, "MAAADDRRCHHHOOODD")
        await MUNNAgalaxy.send_message(kek, "LOOWDEE KEE BAAL")
        await MUNNAgalaxy.send_message(kek, "LAAWDDDEEE KEE BAAL")
        await MUNNAgalaxy.send_message(kek, "JHHAAATTT SEE SHAKAL KE")
        await MUNNAgalaxy.send_message(kek, "CHINARRR MADRCHODDD")
        await MUNNAgalaxy.send_message(kek, "RAMDI KI AULAAD")
        await MUNNAgalaxy.send_message(kek, "TERRIII MAAA KO TERE SAMNE CHOODTA HU")
        await MUNNAgalaxy.send_message(kek, "BSSDDKKEE BAAP SE PANGE LENGE")
        await MUNNAgalaxy.send_message(kek, "YEEE LODDUUU KE BAAL")
        await MUNNAgalaxy.send_message(kek, "JHHAAATTT BHAR KI AAUUKAAT NHI H")
        await MUNNAgalaxy.send_message(kek, "AAYYYY HHHHH BAAAAPPP SSSEEE BHIIIDDHNEE MADARCHHHHOODDD")
        await MUNNAgalaxy.send_message(kek, "BBHHOOSSDDDIIKEEEE APNIII MAA KO DWAI LAA KRRRR DEE")
        await MUNNAgalaxy.send_message(kek, "MAADDRRRCCCHHHOOODDDD TERIIII MAA KIII CCCHHHUUUTTT SSSEEE KHUUNNN NIKALLLL DIYAA HH BBEETTIICCHHOODD")
        await MUNNAgalaxy.send_message(kek, "CHAKKKAAA HHH TUUUU MAAADDRRCHHHOODDDD")
        await MUNNAgalaxy.send_message(kek, "JJHHHAAATEEE JITNI")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "BHIIIII BAAADDIII HOO")
        await MUNNAgalaxy.send_message(kek, "RHHHTTAAAA LUNNNNNDD KEEE NICHEE HI HHHH")
        await MUNNAgalaxy.send_message(kek, "BETICCCHHOOODD")
        await MUNNAgalaxy.send_message(kek, "BHHHHOOOSSSDDIIIIKKEEEE TEEERRIIII AAUUKKAAAT MERA MUUUTT")
        await MUNNAgalaxy.send_message(kek, "PIINEEE KI HHHH USSEEE PIII OR KKKHUUSSHHH")
        await MUNNAgalaxy.send_message(kek, "RAHHHH BETIIICHHOOODDD CHIINARRR")
        await MUNNAgalaxy.send_message(kek, "AAJJJ KEEE BAAD MUNNA SE PANGA")
        await MUNNAgalaxy.send_message(kek, "MATTT LEENNAA MADRCHOODDD")
        await MUNNAgalaxy.send_message(kek, "NHIII TTOO AGLA")
        await MUNNAgalaxy.send_message(kek, "NUMBERRR TERE PURI KHANDANNN")
        await MUNNAgalaxy.send_message(kek, "KIIII ORRTEEEE KAA HOGAAA")
        await MUNNAgalaxy.send_message(kek, "😂")
        await MUNNAgalaxy.send_message(kek, "CHINNARRRR BHOSDIKAAA")
        await MUNNAgalaxy.send_message(kek, "MUNNA SE H BHNCCHOOODDDD")
        await MUNNAgalaxy.send_message(kek, "YAHIII PATAKKK KR")
        await MUNNAgalaxy.send_message(kek, "CHHHOOOODDDD DENGE")
        await MUNNAgalaxy.send_message(kek, "TUMMM JESEE KITNOOO")
        await MUNNAgalaxy.send_message(kek, "KOOO CHOOOOOOODDDDD KRRR CHOD DIYAA GANDUUU")
        await MUNNAgalaxy.send_message(kek, "TELEGRAM ME RAHNA HAI TO MUNNA KO PAPA BOLNA PAREGA WARNA TUMHARII BHN XUDEGI AISE HI ROJ")
        await MUNNAgalaxy.send_message(kek, "😂")
        
        